[package]
name = "brotli-dec-wasm"
version = "1.2.0"
authors = ["myl7 <myl@myl.moe> (https://myl.moe)"]
edition = "2018"
license = "MIT"
description = "Brotli decompressor for browsers and web workers with WASM, but still having a small size (~300K)"
keywords = ["brotli-decompressor", "wasm", "rust"]
repository = "git+ssh://git@github.com/ustclug-dev/brotli-dec-wasm.git"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["size"]
size = ["wee_alloc"]
dev = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
brotli-decompressor = "2.3"
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]
