on:
  push:
    branches:
      - goshujin-sama
  pull_request:
    branches:
      - goshujin-sama
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: cargo install wasm-pack
      - run: npm run build
      - run: npm run pretest
      - run: npm test
