on:
  push:
    branches:
      - goshujin-sama
  pull_request:
    branches:
      - goshujin-sama
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run build
      - run: npm run pretest
      - run: npm test
